# syntax=docker/dockerfile:1
ARG BASE=bitnami/minideb
ARG TAG=bookworm
ARG IMAGE=$BASE:$TAG
FROM $IMAGE
#
# %labels
#
LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source=https://github.com/jhwohlgemuth/gold
LABEL org.opencontainers.image.description="Development environment to build on"
LABEL org.opencontainers.image.licenses=MIT
#
# %arguments
#
ARG VERSION=0.0.1
ARG HOME=/root
ARG DEBIAN_FRONTEND=noninteractive
ARG LANG=en_US.UTF-8
ARG LANGUAGE=en_US:en
ARG LC_ALL=en_US.UTF-8
ARG S6_OVERLAY_VERSION=3.1.5.0
ARG S6_OVERLAY_GITHUB=https://github.com/just-containers/s6-overlay
#
# %environment
#
ENV VERSION="${VERSION}"
ENV TZ=America/New_York
ENV SHELL=/usr/bin/zsh
ENV TERM=xterm-256color
ENV DOTFILES="${HOME}/.dotfiles"
ENV PATH="${PATH}:/usr/local/bin/fn"
ENV PATH="${PATH}:${HOME}/.nix-profile/bin"
ENV PATH="${PATH}:/root/.pixi/bin"
#
# %setup
#
SHELL ["/bin/bash", "-c"]
RUN ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime \
    && echo "${TZ}" > /etc/timezone \
    && mkdir -p \
        "${HOME}/.ssh" \
        /tmp/scripts
#
# %files
#
COPY --chmod=0755 ./provision/scripts/dev/* /tmp/scripts
COPY --chmod=0755 ./provision/functions/* /usr/local/bin
ADD https://github.com/jhwohlgemuth/my-shell-setup.git "${DOTFILES}"
ADD "${S6_OVERLAY_GITHUB}/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz" /tmp
ADD "${S6_OVERLAY_GITHUB}/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz" /tmp
ADD "${S6_OVERLAY_GITHUB}/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch.tar.xz" /tmp
ADD "${S6_OVERLAY_GITHUB}/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-arch.tar.xz" /tmp
#
# %post
#
SHELL ["/bin/bash", "-c"]
RUN /tmp/scripts/install_dependencies.sh \
    && stow --dir "${DOTFILES}" --target "${HOME}" --stow neovim ohmyposh powershell powerlevel10k \
    && /tmp/scripts/configure_locale.sh \
    && /tmp/scripts/install_dotnet.sh \
    && /tmp/scripts/install_ohmyzsh.sh \
    # && /tmp/scripts/install_homebrew.sh \
    # && /tmp/scripts/install_apptainer.sh \
    && /tmp/scripts/install_nix.sh && nix-env --install --file /tmp/scripts/manifest.nix \
    && mv /tmp/scripts/install_cosmopolitan.sh /usr/local/bin/install_cosmopolitan \
    && mv /tmp/scripts/install_cuda.sh /usr/local/bin/install_cuda \
    && mv /tmp/scripts/install_docker.sh /usr/local/bin/install_docker \
    && mv /tmp/scripts/install_musl.sh /usr/local/bin/install_musl \
    && mv /tmp/scripts/install_xr0.sh /usr/local/bin/install_xr0 \
    && /usr/bin/pwsh -Command /tmp/scripts/Install-Modules.ps1 \
    && /tmp/scripts/configure_ohmyzsh.sh \
    # && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" \
    #     && brew bundle --file /tmp/scripts/Brewfile \
    #     && brew cleanup --prune=all \
    #     && eval "$(pkgx integrate)" \
    && find "${NEOVIM_ROOT}" -name "*.vim" -print0 | xargs -0 dos2unix \
    && tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-symlinks-noarch.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-symlinks-arch.tar.xz \
    && cleanup
#
# %runscript
#
WORKDIR /root/dev
HEALTHCHECK NONE
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]