name: NOTEBOOK

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: notebook
  ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - DEV
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - Dockerfile.notebook
      - config/code-server/**
      - config/jupyter/**
      - provision/scripts/notebook/**

jobs:
  build-and-push:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - run: echo "${{ github.actor }}/${{ env.IMAGE_NAME }} will be built and pushed to ${{ env.REGISTRY }}"

      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.ACCESS_TOKEN }}

      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Build and push ${{ env.IMAGE_NAME }} image
        uses: ./.github/actions/build-and-push-image
        with:
          image-name: ${{ env.IMAGE_NAME }}