name: Image Maintenance

permissions:
  packages: write

env:
  ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  KEEP_UNTAGGED_COUNT: 0
  USER: jhwohlgemuth

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Runs at 12:00 AM (midnight) every Sunday

jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Prune Dev
        uses: vlaurin/action-ghcr-prune@0a539594d122b915e71c59733a5b115bfaaf5d52 # v0.5.0
        with:
          container: dev
          token: ${{ env.ACCESS_TOKEN }}
          user: ${{ env.USER }}
          keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
          prune-untagged: true

      - name: Prune Notebook
        uses: vlaurin/action-ghcr-prune@0a539594d122b915e71c59733a5b115bfaaf5d52 # v0.5.0
        with:
          container: notebook
          token: ${{ env.ACCESS_TOKEN }}
          user: ${{ env.USER }}
          keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
          prune-untagged: true

      - name: Prune Rust
        uses: vlaurin/action-ghcr-prune@0a539594d122b915e71c59733a5b115bfaaf5d52 # v0.5.0
        with:
          container: rust
          token: ${{ env.ACCESS_TOKEN }}
          user: ${{ env.USER }}
          keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
          prune-untagged: true

      - name: Prune Web
        uses: vlaurin/action-ghcr-prune@0a539594d122b915e71c59733a5b115bfaaf5d52 # v0.5.0
        with:
          container: web
          token: ${{ env.ACCESS_TOKEN }}
          user: ${{ env.USER }}
          keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
          prune-untagged: true

      - name: Prune Gold
        uses: vlaurin/action-ghcr-prune@0a539594d122b915e71c59733a5b115bfaaf5d52 # v0.5.0
        with:
          container: gold
          token: ${{ env.ACCESS_TOKEN }}
          user: ${{ env.USER }}
          keep-last: ${{ env.KEEP_UNTAGGED_COUNT }}
          prune-untagged: true